spring:
  application:
    name: watchover
  profiles:
    active: prod
    group:
      local: "db-dev, s3, ai"               # 로컬 테스트
      prod: "server-prod, db-prod, s3, ai"  # 운영 서버

  # 공통 DB 설정
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  # 공통 JWT 설정
  jwt:
    secret: "${JWT_SECRET}"
