spring:
  config:
    import: "optional:file:.env.prod[.properties]"
  datasource:
    url: "jdbc:mysql://${DB_URL_PROD}:${DB_PORT_PROD}/${DB_NAME_PROD}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul"
    username: "${DB_USERNAME_PROD}"
    password: "${DB_PASSWORD_PROD}"
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: false