spring:
  application:
    name: watchover
  profiles:
    active: prod
    group:
      local: "db-dev, s3, ai"               # 로컬 테스트
      dev: "server-dev, db-prod, s3, ai"   # 개발 서버 -> 추후에 DB 분리 필요
      prod: "server-prod, db-prod, s3, ai" # 운영 서버