spring:
  config:
    import: "optional:file:.env.prod[.properties]"
  cloud:
    aws:
      s3:
        bucket: ${S3_BUCKET_NAME}
      credentials:
        access-key: ${AWS_ACCESS_KEY}
        secret-key: ${AWS_SECRET_KEY}
      region:
        static: ap-northeast-2